### ISSUE TITLE
Chat Widget's Minimize and Close buttons are not working

### ISSUE THREAD

**Issue by bkskomal** [LiveHelperChat/livehelperchat#1709] opened 2021-10-18 08:59 UTC
Chat Widget's Minimize and Close buttons are not working and the strange thing is there is not exception in the console. Its just clicking on minimize button is not minimizing chat widget and clicking on close button is not closing chat widget
![liveheleprchaterro2](https://user-images.githubusercontent.com/43546103/137700754-84524044-3cdb-4701-935a-c46a7f4e835c.png)
.

**Comment by bkskomal** [comment] 2021-10-18 09:54
This issue is not reproducible on https://demo.livehelperchat.com/site_admin/
This is reproducible when I am adding chat widget to my project.
When I am adding chat widget to just a simplet html page, it's working fine.
It seems something of my project is conflicting with chat widget's functionality.

Can you please suggest, what should I do?

**Comment by PeopleInside** [comment] 2022-02-08 08:23
This issue seems still be opened without updates.
I'm closing this for now, if you feel this need to be kept open please comment below and we will read messages.
For support and not for bug report, you can use the forum https://forum.livehelperchat.com/

**Closed by PeopleInside** 2022-02-08 08:23 UTC
Labels: cannot-reproduce, answered - waiting user reply

**Comment by PeopleInside** [comment] 2022-02-11 15:33
Thank you for the update. I'm glad to read the issue is now resolved.
