### ISSUE TITLE
Uncaught Type Error

### ISSUE THREAD

**Issue by bkonia** [LiveHelperChat/livehelperchat#1391] opened 2019-10-22 21:20 UTC
I'm seeing the following JS error in the console, on every page of my site where the LHC widget appears:

Uncaught Type Error, cannot ready property 'style' of null at https://www.prescientrading.com/livehelperchat/index.php/en/chat/getstatus/(click)/internal/(position)/bottom_right/(ma)/br/(top)/350/(units)/pixels/(leaveamessage)/true/(department)/1/(/theme)/1?r=%2F%2Fwww.prescientrading.com%2Fkb%2Fprescientrader-afl-functions%2F&l=%2F%2Fwww.prescientrading.com%2F:18:1981

It doesn't seem to affect anything, but of course, it's always concerning to see JS errors in the console.

**Comment by PeopleInside** [comment] 2019-10-22 21:33
Hi @bkonia thanks for the report!

- Are you able to find the same error on https://forum.livehelperchat.com/ ?
- What version of PHP are you using?
- What version of live helper chat are you using?

**Comment by bkonia** [comment] 2019-10-22 21:44
No, I don't see the error on your site. I'm using PHP 7.3.7. I'm not sure of the LHC version, but I just downloaded it the other day, so I'm sure it's the latest version. You can view the error on my site at https://www.prescientrading.com. It shows up about 15 seconds after the page loads.

**Comment by PeopleInside** [comment] 2019-10-22 22:00
Hi @bkonia thanks for writing back.
The last version of live helper chat is the 3.25 you can check in the operator settings, update information.

At the moment this issue seems not to be related to live helper chat but the error in your website seems to be caused by your live helper chat instalaltion.

I can see in the error your website is showed as yourdomain:18
So you set something of "strange" in the LHC settings like do compiled the first two field on Misc settings page?

https://demo.livehelperchat.com/site_admin/chat/listchatconfig#!#misc
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/67337851-27fe8780-f528-11e9-82f9-4e5974a7801d.jpg)

**Comment by bkonia** [comment] 2019-10-22 22:15
Yes, I'm using 3.25. There's nothing strange in my Misc screen:

Domain: prescientrading.com
HTTP Mode: https:

If you want, I could give you my LHC login info.

**Comment by PeopleInside** [comment] 2019-10-22 22:22
TypeError more info about this error can be found [here](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default).

![1](https://user-images.githubusercontent.com/5006150/67339034-a52afc00-f52a-11e9-9350-8316a1e368b6.jpg)

![2](https://user-images.githubusercontent.com/5006150/67339039-a6f4bf80-f52a-11e9-85b1-99ef16a4dbc1.jpg)

Umh i don't understand well about code :D as I'm not the programmer of the chat.

You can try to regenerate the mebed code. Have you edited it or just copied and pasted?
I suggest to try also to visit https://htmledit.squarefree.com/ activate browser debug, paste your embed code. The Javascript error is still present?

Sorry but now where I'm (Italy) is late so I'm going to sleep. I will reply here as soon as possibile to every new message you will made.

I have live helper chat installed on my website, is installed on the live helper chat forum... at the moment I'm not able to reproduce this issue. See if you are able to understand what can be the issue.

Have you cusomized the theme of live helper chat i mean used the customtheme folder?
Maybe try to make a test new installation with default setting and check if the mebed code generated give the same issue.

**Comment by PeopleInside** [comment] 2019-10-23 09:06
Hi @bkonia yesterday with you i tried to put your widget embed code on https://htmledit.squarefree.com/ after activated browser debud. no errors so the issue can be related to your theme or where you placed the code. try to regenerate and replace the code.

I will close this issue for now as is not a live helper chat code issue.
If the issue persist you can try to ask help on programing forum like stackoverflow.

I will be happy on hear your feedback and to know you was able to solve the issue.
Have a great day!

**Comment by PeopleInside** [comment] 2019-10-23 09:47
Your issue seems resolved, i cannot see anymore the error.
Nice to see that.

**Comment by bkonia** [comment] 2019-10-23 15:56
It's not really resolved. It's definitely a bug; I just disabled the feature that was causing it.

The problem is caused by the Need Help widget. The setTimeout function you highlighted in your screen shot attempts to set the CSS display attribute to inline-block, after a 15 second delay. The problem is, the widget only displays once per 24-hour period, but the JS code executes every time, so it's trying to set the display attribute of a non-existent object. If you enable the Need Help widget on your site, I'm sure you'll notice the same issue.

The developer needs to fix the code, so it only sets the display attribute when the widget is actually present.

**Comment by PeopleInside** [comment] 2019-10-23 15:58
Assigned to @remdex

**Closed** 2023-09-11 12:16 UTC
Labels: potential-bug
