### ISSUE TITLE
REST API for visitors

### ISSUE THREAD

**Issue by systemmind** [LiveHelperChat/livehelperchat#1369] opened 2019-07-16 13:15 UTC
Hello. It looks your [REST API](https://api.livehelperchat.com/) should be used on the backend only and it is not allowed  to use it by visitors.

But looking at the [architecture picture](https://livehelperchat.com/var/media/images/lhc(1).png) I see that visitors communicate with backend through ajax calls.

I want to write desktop app that works as visitor. Is it possible to use visitor ajax calls API in such case? Is there any documentation how to do this?

Thanks.

**Comment by PeopleInside** [comment] 2019-07-18 16:20
Hi, please look if this can help you: [I'm planning to write a mobile app and would like to use Desktop client API, what I have to know?](https://livehelperchat.com/i-m-planning-to-write-a-mobile-app-and-would-like-to-use-desktop-client-api-what-i-have-to-know-262a.html)

**Comment by PeopleInside** [comment] 2019-07-19 19:54
Is this issue resolved? If i will get no answer i will close it. Seems the question has a possibile answer now so the issue will be closed in the next days.

**Comment by systemmind** [comment] 2019-07-19 20:56
> Hi, please look if this can help you: [I'm planning to write a mobile app and would like to use Desktop client API, what I have to know?](https://livehelperchat.com/i-m-planning-to-write-a-mobile-app-and-would-like-to-use-desktop-client-api-what-i-have-to-know-262a.html)

As I understand this is API to manage system as administrator, isn't it?

Also most of the calls require `chart_id` that is created when new visitor is connected.

Which call creates a new chat there? And another question how to push new message as visitor in specific chat?

Thanks.

**Comment by PeopleInside** [comment] 2019-07-19 20:59
Hi @systemmind - I'm sorry but i'm not the developer of the software :) just giving basic help here as the chat owner is very buy and it's almost alone,

We can try to leave this opened but don't know if and when you can have a reply.
If you need there are [commercial support](https://livehelperchat.com/support-13c.html) but I understand your is just a techical question.

I hope you will be able to figure out, if so please once the issue is resolved close it.

**Comment by systemmind** [comment] 2019-07-19 20:59
> Is this issue resolved? If i will get no answer i will close it. Seems the question has a possibile answer now so the issue will be closed in the next days.

Sorry, I still don't understand is it possible to use existing api to connect to the LCH server as visitor. I have asked more detailed question above.

**Comment by systemmind** [comment] 2019-07-19 21:01
> Hi @systemmind - I'm sorry but i'm not the developer of the software :) just giving basic help here as the chat owner is very buy and it's almost alone,
> 
> We can try to leave this opened but don't know if and when you can have a reply.
> If you need there are [commercial support](https://livehelperchat.com/support-13c.html) but I understand your is just a techical question.
> 
> I hope you will be able to figure out, if so please once the issue is resolved close it.

Yes, keep it opened now please. I have some ideas to research how does extensions work and maybe I just will write a new one and I will close this question when I will found a solution.

Thanks.

**Closed** 2023-09-11 12:22 UTC
Labels: question
