### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by praveenvall** [LiveHelperChat/livehelperchat#868] opened 2016-04-28 05:31 UTC
message deleted

**Comment by praveenvall** [comment] 2016-04-28 05:41
[IMG]http://i66.tinypic.com/11udz86.jpg[/IMG]

**Comment by praveenvall** [comment] 2016-04-28 05:42
`[IMG]http://i66.tinypic.com/11udz86.jpg[/IMG]`

**Comment by praveenvall** [comment] 2016-04-28 05:42
[http://i66.tinypic.com/11udz86.jpg](url)

**Comment by praveenvall** [comment] 2016-04-28 05:44
https://photos.google.com/photo/AF1QipOD79ePqnb1fn2LXayqsdPAX3g922hCq9DuuvTT

**Comment by praveenvall** [comment] 2016-04-28 05:44
`[https://photos.google.com/photo/AF1QipOD79ePqnb1fn2LXayqsdPAX3g922hCq9DuuvTT](url)`

**Comment by PeopleInside** [comment] 2016-04-28 08:00
Hi @praveenvall this topic seems to be invalid.

1. Is not clear to me if I read only here
2. As I know the issue was the same with version 2.44
3. This seems to be not an issue with Live Helper Chat but maybe with your server configuration

Anyway you can keep this open but I think will be closed maybe in a long time as here the activity to fix issue seems to be slowest.

This issue seems to be on your server, not on LHC.

**Comment by praveenvall** [comment] 2016-04-28 09:33
I have installed the LHC through my cpanel  softwares as you suggested.

Everything is working fine withou the custom widget.

I have hosted on my another site with the provided custom widget and everything collapsed.

so the issue is not with the hosting, it is clearly with the customwidget mismatching today with the chat widgets on new versions

**Comment by PeopleInside** [comment] 2016-04-28 09:59
What you mean with "Custom Widget" ?
Issue checked in your case was not in the custom widget but also in the page for start a chat.

Also on https://livehelperchat.com/ I can see there are not custom widget template set and all seems work fine so how to reproduce your issue?

**Comment by praveenvall** [comment] 2016-04-28 11:23
[https://drive.google.com/open?id=0B2MHIbx4_PBpd3R3ODRQMkEwZFE](url)
[https://drive.google.com/open?id=0B2MHIbx4_PBpakg4VkdiX21vNTQ](url)

You may download custom widget from the above and put inside the extensions folders
make changes to your settings.ini as needed and check the issues

**Comment by PeopleInside** [comment] 2016-04-28 11:40
Hi,
this topic will be checked by the chat owner, I think is invalid but is only my think, maybe chat owner can understand better your issue.
Be aware you will not receive fast support, this may stay open without any reply for a long time.

My messages here is for help you to find the right way to understand if your problem is relative to LHC or other things. If your LHC is customized so you have particular extension or template edit is more difficult support you as this can be your issue and not LHC general issue.

Have a great time!

**Comment by praveenvall** [comment] 2016-04-28 11:52
yes I spoke with the chat owner and he asked me to post on GitHub

**Comment by PeopleInside** [comment] 2016-04-28 11:54
OK, thank you and sorry for all message and my intrusion.
Also thanks for that report if is valid for fix a new issue on LHC.

Have a very great time!
Here for help you.

**Closed** 2016-05-02 09:34 UTC
