### ISSUE TITLE
2.52 - bug - Back to chat not work

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/livehelperchat#964] opened 2017-01-11 10:18 UTC
1 started a chat from visitor side
2 accepted chat from operator side
3 user redirected to the survey with the new button function
4 user press back to chat and operator is informed user are back but user still be in the survey also if they complete the survey

_- unable to test in the demo where version is 2.51 -_

test was done in widget with multi department and name required, email not required, message not required. Tested after clean cache and updated version and database in a new browser session with cache cleaned

tested in Firefox 50.1.0

**Comment by remdex** [comment] 2017-01-11 11:22
Was it widget, or popup window?

**Comment by PeopleInside** [comment] 2017-01-11 11:25
widget tested, pop up not tested

**Comment by remdex** [comment] 2017-01-11 11:34
All works here. Closing as invalid, because cannot reproduce. Tested with fresh install.

**Closed by remdex** 2017-01-11 11:34 UTC

**Comment by PeopleInside** [comment] 2017-01-11 12:44
Hi @remdex,
maybe this issue is if the survey is with specific field?
Please see the video in full screen mode:

I AM able to reproduce this. Actually I cannot test in the demo as is older.
As for the previous bug I think also this is a bug or issue. The back to chat button is new and in my case is not working.

VIDEO (Please open in full screen or some video parts will be cut)
http://screencast.com/t/dOSP0ulb61kO

Thank you remdex

**Comment by PeopleInside** [comment] 2017-01-11 15:14
Tested on https://www.softaculous.com/demos/Live_helper_chat 

Unable to reproduce. I added CSS to hide this kind of button on my livechat.
Never idea why it not works, maybe for some settings. Do not know. I have hide the button with CSS

`input.btn:nth-child(4) {
visibility: hidden
}`

I will soon delete also the video attached here.

**Comment by remdex** [comment] 2017-01-11 15:35
Perhaps you have some override etc...

**Comment by PeopleInside** [comment] 2017-01-11 17:00
override in template? I do not have override or customization in the template. will be a mystery :) no errors logs detected... fortunately is not very essential this to me and can be easily solved by hide the button.
Sorry for this report but for me was valid :) and never be able to test on Live helper chat demo but find softaculous demo and all works there :)
