### ISSUE TITLE
Chat widget expanding automatically on Icecat

### ISSUE THREAD

**Issue by Beapal** [LiveHelperChat/livehelperchat#1320] opened 2019-01-28 13:19 UTC
Chat widget expanding automatically on Icecat and Icecat mobile.

Using  Gnu Icecat 60.3 and widget is expanding towards to top slowly on on my site and Livehelperchat official site.

![screenshot from 2019-01-28 18-48-29](https://user-images.githubusercontent.com/37393225/51838789-491aaa80-22ff-11e9-82aa-ff16c8256d1a.png)

**Comment by PeopleInside** [comment] 2019-06-17 13:52
Hi @Beapal is this issue still valid on the last live helper chat version and on the live helper chat website?

If no this issue can be closed as resolved.
If the issue is still present can you provide the steps for reproduce?

Thank you.

**Comment by PeopleInside** [comment] 2019-07-19 19:35
No reply has been made, I will consider this issue resolved.
Please comment if you need to re-open it and we will look on this as soon as possibile and will evalutate to re-open the issue.

**Closed by PeopleInside** 2019-07-19 19:35 UTC
Labels: answered - waiting user reply, question
