### ISSUE TITLE
Questionnaire at the end of the chat

### ISSUE THREAD

**Issue by marcelloinfoweb** [LiveHelperChat/livehelperchat#620] opened 2015-02-06 11:34 UTC
How is it possible to put a questionnaire at the end of each meeting in the chat?

If it's not possible, it would be interesting the idea of having the option to put.

Thank you!

**Comment by remdex** [comment] 2015-02-06 11:35
Duplicate of https://github.com/LiveHelperChat/livehelperchat/issues/545

**Closed by remdex** 2015-02-06 11:35 UTC
Labels: duplicate

**Comment by marcelloinfoweb** [comment] 2015-02-06 13:16
But where is this setting?

**Comment by remdex** [comment] 2015-02-06 13:18
It's not implemented, and without some funding i really do not think so any time soon it will be done, so you can subscribe just to initial issue to see if there will be any updates in the future
