### ISSUE TITLE
Add a button of sending

### ISSUE THREAD

**Issue by LucasVN** [LiveHelperChat/livehelperchat#952] opened 2016-12-21 09:55 UTC
I think that would be a good idea to add a button of sending. In particular for the responsive, certain keyboards have no button to send.

**Comment by PeopleInside** [comment] 2016-12-21 09:57
Hi @LucasVN ,
sorry but this will be closed I think as I told on the forum topic https://forum.livehelperchat.com/viewtopic.php?id=2278 this is a duplicate of https://github.com/LiveHelperChat/livehelperchat/issues/792

Thank you for closing this.

**Closed** 2016-12-21 09:57 UTC

**Comment by LucasVN** [comment] 2016-12-21 09:59
I'm not used to using github issues
