### ISSUE TITLE
Conversion text to emoji

### ISSUE THREAD

**Issue by megabait1212** [LiveHelperChat/livehelperchat#1421] opened 2020-01-24 07:44 UTC
Hi,
I have a problem with emojis when user write something like this :) (or any another one it doesn't convert them) it shows as \u{1F609}. If I select emoji from the provided list, then everything fine. The problem appears from operator and user sides.
![image](https://user-images.githubusercontent.com/5767396/73051855-5aec4a80-3e8c-11ea-85cb-aba4242c3779.png)
I updated to the latest version, but nothing changed. I tried to find any settings to enable conversion but without success. Tables encoding is utf8mb4_unicode. A cache cleared.

**Comment by PeopleInside** [comment] 2020-01-24 07:57
Hi, are you able to reproduce on the demo?
https://livehelperchat.com/demo-12c.html

What version of PHP are you running?

**Comment by megabait1212** [comment] 2020-01-24 08:04
On demo working fine. PHP version 5.6.40

**Comment by PeopleInside** [comment] 2020-01-24 08:06
Hi, thank you so much for your updates!
The issue seems your PHP version outdated.
Please look at this page: https://www.php.net/supported-versions.php

I suggest to update to the last PHP available.

**Comment by megabait1212** [comment] 2020-01-24 08:10
Ok, I will try to change PHP version and update you with new information. Thank you

**Comment by megabait1212** [comment] 2020-01-24 14:21
Thank you for fast response, I close the task because a client not ready to upgrade the PHP version.

**Comment by PeopleInside** [comment] 2020-01-24 15:58
@megabait1212 Thank you for the update and for close the issue as the client can't upgrade PHP

**Comment by megabait1212** [comment] 2020-01-28 07:46
Hi, is it possible to disable the conversion of text to emoji?

**Comment by PeopleInside** [comment] 2020-01-28 09:10
No, it's not and why you need this?
Seems you are having server issue as you showed on the screenshots.
If you solve this server issue i think will be not a problem if the emoji are converted.

**Comment by megabait1212** [comment] 2020-01-28 09:42
The client is not ready to migrate to the new version of PHP

**Comment by remdex** [comment] 2020-01-28 09:48
Actually you should migrate not php version but change mysql table encoding to utf8mb4_unicode_ci it should be fine.

**Comment by megabait1212** [comment] 2020-01-28 10:04
All tables already has encoding utf8mb4_unicode_ci except "lh_doc_share"

**Comment by remdex** [comment] 2020-01-28 10:05
And columns themself?

**Comment by megabait1212** [comment] 2020-01-28 10:07
If you mean table msg and column msg then yes it has encoding to utf8mb4_unicode_ci. Its strange because when I select from list of emoji then it works fine, but when I write manually then it shows encoded text.

**Comment by remdex** [comment] 2020-01-28 10:12
Perhaps it's problem with internal apache encoding. https://stackoverflow.com/questions/913869/how-to-change-the-default-encoding-to-utf-8-for-apache make sure lhc using utf-8 encoding during communication.

**Comment by megabait1212** [comment] 2020-01-28 10:23
Tried didn't help.
![image](https://user-images.githubusercontent.com/5767396/73255510-f3563800-41c8-11ea-81c7-a6e0453308db.png)

**Comment by PeopleInside** [comment] 2020-01-28 10:25
I think the issue can be PHP 5.6 version quite old and maybe dangerous.
I'm not expert of this but i can see is not a good version to use https://www.php.net/supported-versions.php

**Comment by megabait1212** [comment] 2020-01-28 10:28
Screenshot from db
![image](https://user-images.githubusercontent.com/5767396/73255816-8b542180-41c9-11ea-8d6f-f5159f5c350a.png)

**Comment by PeopleInside** [comment] 2020-02-02 15:38
Hi, i will close this has there is no evidence the issue is live helper chat.
Also if the topic will be close we read all message there.

**Closed by PeopleInside** 2020-02-02 15:38 UTC
Labels: answered - waiting user reply, question
