### ISSUE TITLE
Does not working properly with SSL on different domain

### ISSUE THREAD

**Issue by JFOC** [LiveHelperChat/livehelperchat#857] opened 2016-03-31 03:02 UTC
Hello,
I think is not working properly when the livehelper widget were plugin on different host site with SSL.

Host A (hosted livehelper with SSL)
Web B (plugin widget from Host A)

Both Host A and Web B has their own SSL.

Some auto generates javascript is still loading non-SSL on Web B, even I have been set the widget with Browser HTTPS rather than the default or Browser HTTP.

Livehelper version 2.44

**Comment by PeopleInside** [comment] 2016-03-31 05:58
Hi **JFOC**,
this seems to be an invalid GitHub report.

I will not assist you here, for help there are the Live Helper Forum at http://forum.livehelperchat.com

As you can see also in the official website of the live chat there are no issue with widget and SSL so is your issue.
Please before open issue here be sure is a BUG. Also if you resolve your issue please close the topic here.

Have a great day!

**Comment by JFOC** [comment] 2016-03-31 09:02
Because I am thinking this is a bug, when the site loading in SSL but the script still generating non-SSL

**Comment by PeopleInside** [comment] 2016-03-31 09:04
As you can see here: https://livehelperchat.com/ there are no issue with LHC under SSL as you say. Also I AM using LHC under SSL and no Issues.

So maybe is not a BUG is a problem with your settings or server configuration.

**Comment by JFOC** [comment] 2016-03-31 09:06
Did you load the widget outside your primary host of livehelper ?

**Comment by PeopleInside** [comment] 2016-03-31 09:12
Before report here a BUG there are the support forum.
Also you should be able to reproduce the issue on the demo of LHC.

Also again you do not provide any details for understand what should be fine and what is wrong, how to reproduce the error.

When you generate the Embed code you can choose with protocol use, you can also force SSL

**Comment by JFOC** [comment] 2016-03-31 09:16
@PeopleInside What is wrong is not load in SSL for some resources of widget were embed to other web site that are not in same domain with the hosted livehelper.

I've been set to force into SSL mode when generating widget embed codes.

**Comment by PeopleInside** [comment] 2016-03-31 09:17
Can you please provide the URL where you see issue with LHC widget under SSL?

**Comment by JFOC** [comment] 2016-03-31 09:19
Livehelper is hosted on [www.jfoc.net](url) and the widget is embed on [www.cart.web.id](url)

**Comment by PeopleInside** [comment] 2016-03-31 09:32
Your website www.jfoc.net not force SSL so ... this is why in the other website you have issue with SSL elements. You should use the live chat under SSL also in the NON SSL website. 

So you have to force SSL in LHC www.cart.web.id Embed code by selecting Choose prefered http mode or if that not work set also https on settings, live help configuration, chat configuration, MISC

Please enter explicit http mode. Either http: or https:, do not forget : at the end.
here you have to put https

**Comment by PeopleInside** [comment] 2016-04-26 09:13
Hi, seems you have solved your issue.
Your website still not have padlock for issue on your website. You can check at https://www.whynopadlock.com

**Please close this topic as your issue to Live Helper Chat has been resolved in your server side by you with the correct configuration of SSL.**

Thanks

**Closed** 2016-09-08 08:16 UTC
Labels: invalid
