### ISSUE TITLE
Google maps not working

### ISSUE THREAD

**Issue by david-strejc** [LiveHelperChat/livehelperchat#890] opened 2016-07-21 14:36 UTC
Google changed something in their policy and LHC is now not displaying maps.

Is this only my issue?

**Comment by PeopleInside** [comment] 2016-07-21 14:37
Are you on localhost?
I see some post also in the forum about this problem and move from localhost to web resolve the issue. You can use maxmind in geo location.

**Comment by david-strejc** [comment] 2016-07-21 15:04
I am using maxmind - geo locating works.

But maps says:

Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

This is due to change in google API for maps here:

https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by PeopleInside** [comment] 2016-07-21 15:06
Are you on localhost or are you online in online VPS or dedicated server?

**Comment by PeopleInside** [comment] 2016-07-21 15:17
** Issue confirmed **

How to reproduce:
Try to open visitor maps liveheperchat/index.php/site_admin/#/map

the maps are not showed well also the console give api error.

Please be more detailed when you report a BUG or ISSUE.

I AM with version 2.40 because the last version has STRONG BUG not resolved: https://github.com/LiveHelperChat/livehelperchat/issues/836

but seems in the demo of live helper chat all work fine also if the version is not the last because demo version is 2.44 the last version available is 2.46

I cannot use all this new version because bugged here:  https://github.com/LiveHelperChat/livehelperchat/issues/836

Google Maps seems not work with MaxMind active.

Thank you for reporting.

**Comment by PeopleInside** [comment] 2016-07-21 15:22
If the most recent version of LHC has resolved this issue please FIX this BUG who let me unable to update to the last version: https://github.com/LiveHelperChat/livehelperchat/issues/836

This is very strong BUG who broke the offline module

**Comment by remdex** [comment] 2016-09-08 12:41
Fixed in new commits. There will be new configuration parameter in geo configuration window.

**Closed** 2016-09-08 12:41 UTC
Labels: enhancement
