### ISSUE TITLE
Idea - Video streaming

### ISSUE THREAD

**Issue by danielc1234** [LiveHelperChat/livehelperchat#610] opened 2015-01-21 22:21 UTC
Hi Remigijus,

I just saw a commercial on TV about a chat/customer service that uses a software that has the ability to have video. So that the customer and operator can look at each other while talking about their issues or sales questions.

Thought this would be a really nice feature if there was a way to incorporate that. I cannot think of another chat software that has it.... :)

Daniel

**Comment by remdex** [comment] 2015-01-22 05:57
Actually there is some. But the tricky part is it's not so SIMPLE. And actually your issue is duplicate of 
https://github.com/LiveHelperChat/livehelperchat/issues/173

**Closed by remdex** 2015-01-22 05:57 UTC
Labels: duplicate
