### ISSUE TITLE
Unable to install live chat helper in osticket

### ISSUE THREAD

**Issue by Sabyainnovative** [LiveHelperChat/livehelperchat#831] opened 2016-02-03 13:29 UTC
I have tried the process as shown in installation txt file, but still live chat is not working in my domain.
Please help me 
Thank you
##

**Comment by PeopleInside** [comment] 2016-02-03 13:31
Hi,
this is place for bug report or feature request. For support please open a topic in the forum https://forum.livehelperchat.com/viewforum.php?id=1 and please close this topic on GitHub as is not a bug or feature request. Thank you.

**Closed** 2016-12-08 11:02 UTC
