### ISSUE TITLE
Double escaping

### ISSUE THREAD

**Issue by ailaG** [LiveHelperChat/livehelperchat#1549] opened 2020-10-01 01:56 UTC
Some strings seem to be escaped twice, and thus, at least in the Hebrew version, appear escaped to the user.
Two such examples are 
1. The breadcrumbs at <url>/index.php/site_admin/chatsettings/startchatformsettings , the last one should say `צ'אט`, but it says `צ#039;אט` instead.
The title right under it ("Start Chat Form") is okay.
![lhc_esc1b](https://user-images.githubusercontent.com/859287/94757047-d8fcdb80-03a1-11eb-8dcb-6607463febf1.png)

2. The form the user gets when no operators are available, the e-mail field should say `דוא"ל`, but it says `דוא&quot;ל` instead.

![lhc_esc1](https://user-images.githubusercontent.com/859287/94757081-f5991380-03a1-11eb-9344-c344072202fe.png)

---

As a side note, the letters switching places is okay (`דוא"ל` vs `דוא&quot;ל`, the letters on the left and the right are swapped)  - this is okay, this is normal bidi behavior and is not a bug. The htmlentities are the bug.

**Comment by remdex** [comment] 2020-10-01 03:41
Second one i could not reproduce. So most likely already fixed in some of the updates.
![image](https://user-images.githubusercontent.com/1146085/94762675-11f07c80-03b1-11eb-8db5-6046cf847b6e.png)
![image](https://user-images.githubusercontent.com/1146085/94762683-174dc700-03b1-11eb-9747-a5887e57d438.png)

**Comment by remdex** [comment] 2020-10-01 03:44
Managed reproduce and second one, reopened :D

**Comment by remdex** [comment] 2020-10-01 04:18
Please update to master branch and all should be good after you clear a cache.

**Closed** 2020-10-01 04:18 UTC
Labels: bug
