### ISSUE TITLE
Embed chat not works correcly with PHP7.4

### ISSUE THREAD

**Issue by CryptorClub** [LiveHelperChat/livehelperchat#1429] opened 2020-02-05 19:30 UTC
Admin panel works, but in the same time do not count online visitors. Embed chat widget/page also not worked correctly :(

**Comment by PeopleInside** [comment] 2020-02-05 20:52
Hi @CryptorClub,
this seems to be not an issue for GitHub. 
You can use the live helper chat [forum](https://forum.livehelperchat.com/) for report issue you are having with live helper chat.

Can you share the site where the embed code is in the source code?

**Comment by CryptorClub** [comment] 2020-02-05 21:27
Thanks for answer. No source code not published. 
Its 100% server side problem, not where embed code published.
When I set to PHP7.0 all fine, when switching to 7.4 - not works...

embed code just JavaScript - its running on users side, 
server, as a response receiver or JavaScript producer (with php7.4) can't operate it correctly.

**Comment by PeopleInside** [comment] 2020-02-05 21:29
Can you please test with PHP 7.3?
If the issue is only with PHP 7.4 can you please check and report error logs?

**Comment by CryptorClub** [comment] 2020-02-05 21:51
Just checked. With 7.3 worked correctly! Seems that something missed with modifying for 7.4

**Comment by PeopleInside** [comment] 2020-02-05 22:00
OK so i don't know if live helper chat is ready for PHP 7.4 but thanks for opening an issue.
Please check PHP error log also server error log.
If you can paste something this can help.

I will assign this issue to the chat owner.

**Comment by PeopleInside** [comment] 2020-02-05 22:04
Please include also the version of live helper chat that you are using. Be sure is the latest one.

**Comment by CryptorClub** [comment] 2020-02-06 01:16
I've downloaded latest version.
Seems same behaviour on 7.2, 7.3, 7.4

The users, that existed in db visible in online users. Seems, that versions 7.2, 7.3, 7.4 can't create new entry.

I'll write more info, when research it

**Comment by remdex** [comment] 2020-02-06 04:59
Just see cache/default.log perhaps there you will find something.

**Comment by CryptorClub** [comment] 2020-02-06 05:37
@remdex thanks for answer. In this log found, that it was MaxMind module error. After turning if off in geodetection configuration - start works online users display

**Comment by PeopleInside** [comment] 2020-02-06 09:13
Hi @CryptorClub thanks for the updated.
I'm closing this.

**Closed by PeopleInside** 2020-02-06 09:13 UTC
Labels: question
