### ISSUE TITLE
Sound is not working on Chrome / Notifications requests does not work

### ISSUE THREAD

**Issue by ninoskuflic** [LiveHelperChat/livehelperchat#1654] opened 2021-04-09 15:33 UTC
Hi,
when a user sends a message and the agent replies, the sound is not being played. When clicking "Request notification permission" here /index.php/site_admin/user/account#!#notifications, nothing happens.

Can you advise on this? :)

Thanks,

**Comment by remdex** [comment] 2021-04-09 15:56
Not much, if you already granted permissions notifications would show. Https should be enabled.

As for sounds it's played after referesh and if there was some interaction with page itself.

**Comment by ninoskuflic** [comment] 2021-04-09 16:01
HTTPS is enabled. I did not grant permission, and when I click on that button, nothing happens. There is interaction with the page but the sound is still an issue.

**Comment by remdex** [comment] 2021-04-09 16:03
Well here i don't have that issue :) and there is always commercial support if you need one. As long i can't reproduce I can't help :)

**Comment by PeopleInside** [comment] 2021-04-09 16:12
Hi @ninoskuflic 

- are you sure there are no issue with some extension you may have active on Chrome?
- issue with sound can be reproduced also in the live helper chat demo https://livehelperchat.com/demo-12c.html and if yes with one steps?
- have you tried a different browser like Firefox for example?

As remdex said you will not hear the message sound if you are active focused on the operator "console" or if the visitor is active in the chat widget. Usually sound should be played if you are visiting another page for example and you have chat widget (visitor) open in inactive tab.

Be sure also all sound settings are active and remember can be useful provide here exact steps for reproduce the issue, possibility in the live helper chat demo.

**Comment by PeopleInside** [comment] 2022-02-08 09:00
I'm closing this as no answer has been added after my reply.
If you still need support you can simply reply to this topic, also if closed.
Thanks.

**Closed by PeopleInside** 2022-02-08 09:00 UTC
Labels: answered - waiting user reply
