### ISSUE TITLE
No sound for new chats

### ISSUE THREAD

**Issue by fcordeiro** [LiveHelperChat/livehelperchat#811] opened 2015-12-21 21:07 UTC
After the most recent Google Chrome update, if I left the page for a certain while the next chats will made no sound until I select the tab where the chat is. I think it's because now Google Chrome will remove that tab from memory, if not used for a specific time.

**Comment by PeopleInside** [comment] 2015-12-21 21:11
Yes, confirmed.
I don't know if is a Chrome bug... for this issue I just unistalled Chrome and using now other browser.

remdex this issue can fixed?
I have also tried to ask in the forum but no reply.

Now is difficult find my topic in the forum. I Am trying.. as I can't open my profile and see my topic.. or maybe was a message to rem.. I remember to have alerted and discussed of the same new issue.

**Comment by remdex** [comment] 2016-01-02 17:07
Sorry but cannot reproduce.... Closing as cannot reproduce. I closed a window and started chat on another browser and i received notification and sound notification. If chrome kills something in the background i cannot do much in any case.

**Comment by fcordeiro** [comment] 2016-01-02 17:24
You need to leave the browser for at least one hour. After this time without new chats, new incoming requests will not cause any sound.

**Comment by remdex** [comment] 2016-01-02 17:33
I cannot help with this case i'm afraid... Unless you point to some issue
resolve page in google forum etc.

On 2 January 2016 at 19:24, Fernando Cordeiro <notifications@github.com>
wrote:

> You need to leave the browser for at least one hour. After this time
> without new chats, new incoming requests will not cause any sound.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiveHelperChat/livehelperchat/issues/811#issuecomment-168409271>
> .
>



-- 
Sincerely,
Remigijus Kiminas

**Comment by lipsum83** [comment] 2016-02-29 18:43
I was able to reproduce this issue, not sure if a Chrome only thing yet, as some other people in my team told me that the same thing happen to them when using firefox. I will try to verify that last statement in the upcoming hours, by the way, as reported before, it only happens when there has been some time without new chats.

**Comment by fcordeiro** [comment] 2016-02-29 18:53
Try to access chrome://flags/#automatic-tab-discarding and change tab discarding from "standard" to "disabled".

**Comment by fcordeiro** [comment] 2016-02-29 18:53
Try to access chrome://flags/#automatic-tab-discarding and change tab discarding from "standard" to "disabled".

**Comment by PeopleInside** [comment] 2016-02-29 21:13
Hi, thanks for the updates.
Is some times I cannot see remdex active in the forum, here in GitHub and maybe also via email.
@fcordeiro , @lipsum83 do you think to know why this issue happen and affect Chrome?

I don't know Firefox, from when i discover this issue I removed Chrome from my PC because I was using only for the live chat, usually I use Firefox but don't want use the same browser I use for do search and work on Internet for the live chat so now I AM using Chromodo and the issue is disapered to me.

Maybe if there is a way to be sure this issue is a Live Helper Issue and not Chrome Issue... I suggest to open new BUG report and refer this one (so for refer this one in the new just copy the URL of this discussion into the new) BUT before this maybe will be good for Chrome user ask help in the Chrome support forum and see what happen... if they can help to understand if is Live Helper Chat Issue or browser Issue.

If the issue is also in Firefox should be also discussed in Firefox Topic. Here @remdex has closed this topic for now and consider resolved as they are unable to reproduce and see this error in Live Helper Chat.

Thank you!

**Comment by PeopleInside** [comment] 2016-03-01 10:03
OK today Chromodo has been update and have the same issue as Chrome.
As Chromodo seems based on Chrome I suppose this is not Live Helper Chat BUG but issue with Chrome.

In Firefox I was unable to reproduce for now and never tested Firefox LHC on 2016 but if the issue will be present also in the last version of Firefox maybe something in the new browser cause the issue.

I will resume Chromodo 45.8.12.391 who is not affected and report to Comdo the issue. 
I will now also try again last version of Chrome and if I can be able to reproduce notification sound issue I will look where alert Chrome of BUG.

**Comment by juanluisbaptiste** [comment] 2016-07-22 03:13
It also happens to me on unbuntu 16.04 with chromium 51.0.2704.79 Ubuntu 16.04 (64-bit)

**Comment by PeopleInside** [comment] 2016-07-22 06:32
Chrome is the problem. Is Chrome who changed something so when the Chrome window is minimized or not in first view notification sound are not reproduced. You should report to Google.

**Comment by fcordeiro** [comment] 2016-07-24 19:15
It is not a bug with Chrome, but a new default behavior of the browser. I no longer use live chat, but you tried to disable the tab-discarding feature as I mentioned above?

**Comment by remdex** [comment] 2016-12-08 13:35
Please test and let me know does it helped. For me seems it helped

**Closed** 2016-12-08 13:34 UTC
Labels: cannot-reproduce, enhancement

**Comment by Apanterado** [comment] 2018-02-28 17:52
or instead of uninstalling the chrome, just clean (delete) the cookies for the URL you are working on and having the issue.
