### ISSUE TITLE
iPad and iPhone is not showing LHC widget anymore

### ISSUE THREAD

**Issue by xchillsx** [LiveHelperChat/livehelperchat#757] opened 2015-09-08 19:27 UTC
All,

i figured out, that soehow with the latest version the Apple *iDevices* are not working anymore.
What could be the reason?
Any idea what logfile I could check to get further Details?

**Thank you in advance**
Heiko

P.S: latest version installed. Cache cleaned. System restarted.

**Comment by PeopleInside** [comment] 2015-09-09 08:24
Hi @xchillsx, 
thank you for your report!

I AM sorry but **your report seems to be INVALID**
If you have personal issue on your website you should try to ask questions in the live helper forum at this address: https://forum.livehelperchat.com not here as is not a BUG report.

Before open an issue here you should test before.. test is not only your issue.
How to do that? Simply check on your iPad or Apple device if the widget of https://livehelperchat.com is visible.

I tested the last LHC version on my website and also on the demo live helper chat website and the widget is showed on the Apple browser correctly.
I can see the online widget without issues.

Please check better, verify is not only your issue and if is remember to post questions on the forum not here.
As you verify is not a BUG of the software you can close this topic here.

Thank you!

**your report seems to be invalid** is no possible to reproduce in official demo and in my personal website with the last version 37 of LHC

**Comment by remdex** [comment] 2015-09-09 08:25
As @PeopleInside mentioned it's invalid. Closing as invalid issue.

**Closed by remdex** 2015-09-09 08:25 UTC
Labels: invalid
